// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: bff/bff.proto

package bff

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Health check request message - no parameters required
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_bff_bff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_bff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_bff_bff_proto_rawDescGZIP(), []int{0}
}

// Health check response containing service status information
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service status indicator (e.g., "healthy", "degraded", "unhealthy")
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_bff_bff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_bff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_bff_bff_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Request message for creating a new BFF record
type CreateBFFRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the user making the request (UUID format)
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Amount value in the base currency unit (e.g., dollars, not cents)
	Amount        float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBFFRequest) Reset() {
	*x = CreateBFFRequest{}
	mi := &file_bff_bff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBFFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBFFRequest) ProtoMessage() {}

func (x *CreateBFFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_bff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBFFRequest.ProtoReflect.Descriptor instead.
func (*CreateBFFRequest) Descriptor() ([]byte, []int) {
	return file_bff_bff_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBFFRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateBFFRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Response message for BFF record creation
type CreateBFFResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation status indicating success or failure ("success", "failed", "pending")
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Confirmed amount value that was processed
	Amount        float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBFFResponse) Reset() {
	*x = CreateBFFResponse{}
	mi := &file_bff_bff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBFFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBFFResponse) ProtoMessage() {}

func (x *CreateBFFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_bff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBFFResponse.ProtoReflect.Descriptor instead.
func (*CreateBFFResponse) Descriptor() ([]byte, []int) {
	return file_bff_bff_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBFFResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateBFFResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_bff_bff_proto protoreflect.FileDescriptor

const file_bff_bff_proto_rawDesc = "" +
	"\n" +
	"\rbff/bff.proto\x12\x03bff\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"C\n" +
	"\x10CreateBFFRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"C\n" +
	"\x11CreateBFFResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount2\xb6\x01\n" +
	"\n" +
	"BFFService\x12X\n" +
	"\vHealthCheck\x12\x17.bff.HealthCheckRequest\x1a\x18.bff.HealthCheckResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/bff/health\x12N\n" +
	"\tCreateBFF\x12\x15.bff.CreateBFFRequest\x1a\x16.bff.CreateBFFResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/v1/bffB\x82\x02\x92A\x8d\x01\x12\x8a\x01\n" +
	"\aBFF API\x12zBackend-For-Frontend service API providing aggregated data access and business logic orchestration for client applications2\x031.0\n" +
	"\acom.bffB\bBffProtoP\x01Z0github.com/sundowndev/grpc-api-example/proto/bff\xa2\x02\x03BXX\xaa\x02\x03Bff\xca\x02\x03Bff\xe2\x02\x0fBff\\GPBMetadata\xea\x02\x03Bffb\x06proto3"

var (
	file_bff_bff_proto_rawDescOnce sync.Once
	file_bff_bff_proto_rawDescData []byte
)

func file_bff_bff_proto_rawDescGZIP() []byte {
	file_bff_bff_proto_rawDescOnce.Do(func() {
		file_bff_bff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bff_bff_proto_rawDesc), len(file_bff_bff_proto_rawDesc)))
	})
	return file_bff_bff_proto_rawDescData
}

var file_bff_bff_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bff_bff_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),  // 0: bff.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 1: bff.HealthCheckResponse
	(*CreateBFFRequest)(nil),    // 2: bff.CreateBFFRequest
	(*CreateBFFResponse)(nil),   // 3: bff.CreateBFFResponse
}
var file_bff_bff_proto_depIdxs = []int32{
	0, // 0: bff.BFFService.HealthCheck:input_type -> bff.HealthCheckRequest
	2, // 1: bff.BFFService.CreateBFF:input_type -> bff.CreateBFFRequest
	1, // 2: bff.BFFService.HealthCheck:output_type -> bff.HealthCheckResponse
	3, // 3: bff.BFFService.CreateBFF:output_type -> bff.CreateBFFResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bff_bff_proto_init() }
func file_bff_bff_proto_init() {
	if File_bff_bff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bff_bff_proto_rawDesc), len(file_bff_bff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bff_bff_proto_goTypes,
		DependencyIndexes: file_bff_bff_proto_depIdxs,
		MessageInfos:      file_bff_bff_proto_msgTypes,
	}.Build()
	File_bff_bff_proto = out.File
	file_bff_bff_proto_goTypes = nil
	file_bff_bff_proto_depIdxs = nil
}
