// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	DeletePaymentMethodByCode(ctx context.Context, paymentMethodCode string) error
	DisablePaymentMethodByCode(ctx context.Context, paymentMethodCode string) error
	EnablePaymentMethodByCode(ctx context.Context, paymentMethodCode string) error
	GetPaymentMethodByCode(ctx context.Context, paymentMethodCode string) (PaymentMethod, error)
	ListPaymentMethods(ctx context.Context) ([]PaymentMethod, error)
}

var _ Querier = (*Queries)(nil)
