// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: assets/payments/cards.proto

package payments

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CardBrand represents the brand/type of a payment card
type CardBrand int32

const (
	CardBrand_CARD_BRAND_UNSPECIFIED      CardBrand = 0
	CardBrand_CARD_BRAND_VISA             CardBrand = 1
	CardBrand_CARD_BRAND_MASTERCARD       CardBrand = 2
	CardBrand_CARD_BRAND_AMERICAN_EXPRESS CardBrand = 3
	CardBrand_CARD_BRAND_DISCOVER         CardBrand = 4
	CardBrand_CARD_BRAND_DINERS_CLUB      CardBrand = 5
	CardBrand_CARD_BRAND_JCB              CardBrand = 6
	CardBrand_CARD_BRAND_UNIONPAY         CardBrand = 7
)

// Enum value maps for CardBrand.
var (
	CardBrand_name = map[int32]string{
		0: "CARD_BRAND_UNSPECIFIED",
		1: "CARD_BRAND_VISA",
		2: "CARD_BRAND_MASTERCARD",
		3: "CARD_BRAND_AMERICAN_EXPRESS",
		4: "CARD_BRAND_DISCOVER",
		5: "CARD_BRAND_DINERS_CLUB",
		6: "CARD_BRAND_JCB",
		7: "CARD_BRAND_UNIONPAY",
	}
	CardBrand_value = map[string]int32{
		"CARD_BRAND_UNSPECIFIED":      0,
		"CARD_BRAND_VISA":             1,
		"CARD_BRAND_MASTERCARD":       2,
		"CARD_BRAND_AMERICAN_EXPRESS": 3,
		"CARD_BRAND_DISCOVER":         4,
		"CARD_BRAND_DINERS_CLUB":      5,
		"CARD_BRAND_JCB":              6,
		"CARD_BRAND_UNIONPAY":         7,
	}
)

func (x CardBrand) Enum() *CardBrand {
	p := new(CardBrand)
	*p = x
	return p
}

func (x CardBrand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardBrand) Descriptor() protoreflect.EnumDescriptor {
	return file_assets_payments_cards_proto_enumTypes[0].Descriptor()
}

func (CardBrand) Type() protoreflect.EnumType {
	return &file_assets_payments_cards_proto_enumTypes[0]
}

func (x CardBrand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardBrand.Descriptor instead.
func (CardBrand) EnumDescriptor() ([]byte, []int) {
	return file_assets_payments_cards_proto_rawDescGZIP(), []int{0}
}

// CardStatus represents the status of a card
type CardStatus int32

const (
	CardStatus_CARD_STATUS_UNSPECIFIED CardStatus = 0
	CardStatus_CARD_STATUS_PENDING     CardStatus = 1
	CardStatus_CARD_STATUS_ACTIVE      CardStatus = 2
	CardStatus_CARD_STATUS_INACTIVE    CardStatus = 3
)

// Enum value maps for CardStatus.
var (
	CardStatus_name = map[int32]string{
		0: "CARD_STATUS_UNSPECIFIED",
		1: "CARD_STATUS_PENDING",
		2: "CARD_STATUS_ACTIVE",
		3: "CARD_STATUS_INACTIVE",
	}
	CardStatus_value = map[string]int32{
		"CARD_STATUS_UNSPECIFIED": 0,
		"CARD_STATUS_PENDING":     1,
		"CARD_STATUS_ACTIVE":      2,
		"CARD_STATUS_INACTIVE":    3,
	}
)

func (x CardStatus) Enum() *CardStatus {
	p := new(CardStatus)
	*p = x
	return p
}

func (x CardStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_assets_payments_cards_proto_enumTypes[1].Descriptor()
}

func (CardStatus) Type() protoreflect.EnumType {
	return &file_assets_payments_cards_proto_enumTypes[1]
}

func (x CardStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardStatus.Descriptor instead.
func (CardStatus) EnumDescriptor() ([]byte, []int) {
	return file_assets_payments_cards_proto_rawDescGZIP(), []int{1}
}

// Card represents a payment card
type Card struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganisationId  string                 `protobuf:"bytes,2,opt,name=organisation_id,json=organisationId,proto3" json:"organisation_id,omitempty"`
	VgsVaultToken   string                 `protobuf:"bytes,3,opt,name=vgs_vault_token,json=vgsVaultToken,proto3" json:"vgs_vault_token,omitempty"`
	CardNumberToken string                 `protobuf:"bytes,4,opt,name=card_number_token,json=cardNumberToken,proto3" json:"card_number_token,omitempty"`
	CardCvcToken    string                 `protobuf:"bytes,5,opt,name=card_cvc_token,json=cardCvcToken,proto3" json:"card_cvc_token,omitempty"`
	CardExpToken    string                 `protobuf:"bytes,6,opt,name=card_exp_token,json=cardExpToken,proto3" json:"card_exp_token,omitempty"`
	LastFour        string                 `protobuf:"bytes,7,opt,name=last_four,json=lastFour,proto3" json:"last_four,omitempty"`
	Brand           CardBrand              `protobuf:"varint,8,opt,name=brand,proto3,enum=payments.CardBrand" json:"brand,omitempty"`
	ExpiryMonth     int32                  `protobuf:"varint,9,opt,name=expiry_month,json=expiryMonth,proto3" json:"expiry_month,omitempty"`
	ExpiryYear      int32                  `protobuf:"varint,10,opt,name=expiry_year,json=expiryYear,proto3" json:"expiry_year,omitempty"`
	BindCardUrl     string                 `protobuf:"bytes,11,opt,name=bind_card_url,json=bindCardUrl,proto3" json:"bind_card_url,omitempty"`
	Status          CardStatus             `protobuf:"varint,12,opt,name=status,proto3,enum=payments.CardStatus" json:"status,omitempty"`
	IsDefault       bool                   `protobuf:"varint,13,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO 8601 date string
	UpdatedAt       string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // ISO 8601 date string
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_assets_payments_cards_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_assets_payments_cards_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_assets_payments_cards_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetOrganisationId() string {
	if x != nil {
		return x.OrganisationId
	}
	return ""
}

func (x *Card) GetVgsVaultToken() string {
	if x != nil {
		return x.VgsVaultToken
	}
	return ""
}

func (x *Card) GetCardNumberToken() string {
	if x != nil {
		return x.CardNumberToken
	}
	return ""
}

func (x *Card) GetCardCvcToken() string {
	if x != nil {
		return x.CardCvcToken
	}
	return ""
}

func (x *Card) GetCardExpToken() string {
	if x != nil {
		return x.CardExpToken
	}
	return ""
}

func (x *Card) GetLastFour() string {
	if x != nil {
		return x.LastFour
	}
	return ""
}

func (x *Card) GetBrand() CardBrand {
	if x != nil {
		return x.Brand
	}
	return CardBrand_CARD_BRAND_UNSPECIFIED
}

func (x *Card) GetExpiryMonth() int32 {
	if x != nil {
		return x.ExpiryMonth
	}
	return 0
}

func (x *Card) GetExpiryYear() int32 {
	if x != nil {
		return x.ExpiryYear
	}
	return 0
}

func (x *Card) GetBindCardUrl() string {
	if x != nil {
		return x.BindCardUrl
	}
	return ""
}

func (x *Card) GetStatus() CardStatus {
	if x != nil {
		return x.Status
	}
	return CardStatus_CARD_STATUS_UNSPECIFIED
}

func (x *Card) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Card) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Card) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// CreateCardRequest represents a request to create a new card
type CreateCardRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganisationId string                 `protobuf:"bytes,1,opt,name=organisation_id,json=organisationId,proto3" json:"organisation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_assets_payments_cards_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_payments_cards_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_assets_payments_cards_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCardRequest) GetOrganisationId() string {
	if x != nil {
		return x.OrganisationId
	}
	return ""
}

// CreateCardResponse represents a response to creating a new card
type CreateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardResponse) Reset() {
	*x = CreateCardResponse{}
	mi := &file_assets_payments_cards_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardResponse) ProtoMessage() {}

func (x *CreateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assets_payments_cards_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardResponse.ProtoReflect.Descriptor instead.
func (*CreateCardResponse) Descriptor() ([]byte, []int) {
	return file_assets_payments_cards_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

// DeleteCardRequest represents a request to delete a card
type DeleteCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardRequest) Reset() {
	*x = DeleteCardRequest{}
	mi := &file_assets_payments_cards_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardRequest) ProtoMessage() {}

func (x *DeleteCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_payments_cards_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return file_assets_payments_cards_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

// DeleteCardResponse represents a response to deleting a card
type DeleteCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardResponse) Reset() {
	*x = DeleteCardResponse{}
	mi := &file_assets_payments_cards_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardResponse) ProtoMessage() {}

func (x *DeleteCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assets_payments_cards_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardResponse.ProtoReflect.Descriptor instead.
func (*DeleteCardResponse) Descriptor() ([]byte, []int) {
	return file_assets_payments_cards_proto_rawDescGZIP(), []int{4}
}

// GetCardsRequest represents a request to get all cards for a customer
type GetCardsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganisationId string                 `protobuf:"bytes,1,opt,name=organisation_id,json=organisationId,proto3" json:"organisation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCardsRequest) Reset() {
	*x = GetCardsRequest{}
	mi := &file_assets_payments_cards_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsRequest) ProtoMessage() {}

func (x *GetCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_payments_cards_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsRequest.ProtoReflect.Descriptor instead.
func (*GetCardsRequest) Descriptor() ([]byte, []int) {
	return file_assets_payments_cards_proto_rawDescGZIP(), []int{5}
}

func (x *GetCardsRequest) GetOrganisationId() string {
	if x != nil {
		return x.OrganisationId
	}
	return ""
}

// GetCardsResponse represents a response to getting all cards for a customer
type GetCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsResponse) Reset() {
	*x = GetCardsResponse{}
	mi := &file_assets_payments_cards_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsResponse) ProtoMessage() {}

func (x *GetCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assets_payments_cards_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsResponse.ProtoReflect.Descriptor instead.
func (*GetCardsResponse) Descriptor() ([]byte, []int) {
	return file_assets_payments_cards_proto_rawDescGZIP(), []int{6}
}

func (x *GetCardsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

// SetDefaultCardRequest represents a request to set a card as default
type SetDefaultCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultCardRequest) Reset() {
	*x = SetDefaultCardRequest{}
	mi := &file_assets_payments_cards_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultCardRequest) ProtoMessage() {}

func (x *SetDefaultCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_payments_cards_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultCardRequest.ProtoReflect.Descriptor instead.
func (*SetDefaultCardRequest) Descriptor() ([]byte, []int) {
	return file_assets_payments_cards_proto_rawDescGZIP(), []int{7}
}

func (x *SetDefaultCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

// SetDefaultCardResponse represents a response to setting a card as default
type SetDefaultCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultCardResponse) Reset() {
	*x = SetDefaultCardResponse{}
	mi := &file_assets_payments_cards_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultCardResponse) ProtoMessage() {}

func (x *SetDefaultCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assets_payments_cards_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultCardResponse.ProtoReflect.Descriptor instead.
func (*SetDefaultCardResponse) Descriptor() ([]byte, []int) {
	return file_assets_payments_cards_proto_rawDescGZIP(), []int{8}
}

var File_assets_payments_cards_proto protoreflect.FileDescriptor

const file_assets_payments_cards_proto_rawDesc = "" +
	"\n" +
	"\x1bassets/payments/cards.proto\x12\bpayments\"\x9a\x04\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganisation_id\x18\x02 \x01(\tR\x0eorganisationId\x12&\n" +
	"\x0fvgs_vault_token\x18\x03 \x01(\tR\rvgsVaultToken\x12*\n" +
	"\x11card_number_token\x18\x04 \x01(\tR\x0fcardNumberToken\x12$\n" +
	"\x0ecard_cvc_token\x18\x05 \x01(\tR\fcardCvcToken\x12$\n" +
	"\x0ecard_exp_token\x18\x06 \x01(\tR\fcardExpToken\x12\x1b\n" +
	"\tlast_four\x18\a \x01(\tR\blastFour\x12)\n" +
	"\x05brand\x18\b \x01(\x0e2\x13.payments.CardBrandR\x05brand\x12!\n" +
	"\fexpiry_month\x18\t \x01(\x05R\vexpiryMonth\x12\x1f\n" +
	"\vexpiry_year\x18\n" +
	" \x01(\x05R\n" +
	"expiryYear\x12\"\n" +
	"\rbind_card_url\x18\v \x01(\tR\vbindCardUrl\x12,\n" +
	"\x06status\x18\f \x01(\x0e2\x14.payments.CardStatusR\x06status\x12\x1d\n" +
	"\n" +
	"is_default\x18\r \x01(\bR\tisDefault\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\"<\n" +
	"\x11CreateCardRequest\x12'\n" +
	"\x0forganisation_id\x18\x01 \x01(\tR\x0eorganisationId\"8\n" +
	"\x12CreateCardResponse\x12\"\n" +
	"\x04card\x18\x01 \x01(\v2\x0e.payments.CardR\x04card\",\n" +
	"\x11DeleteCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\"\x14\n" +
	"\x12DeleteCardResponse\":\n" +
	"\x0fGetCardsRequest\x12'\n" +
	"\x0forganisation_id\x18\x01 \x01(\tR\x0eorganisationId\"8\n" +
	"\x10GetCardsResponse\x12$\n" +
	"\x05cards\x18\x01 \x03(\v2\x0e.payments.CardR\x05cards\"0\n" +
	"\x15SetDefaultCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\"\x18\n" +
	"\x16SetDefaultCardResponse*\xda\x01\n" +
	"\tCardBrand\x12\x1a\n" +
	"\x16CARD_BRAND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCARD_BRAND_VISA\x10\x01\x12\x19\n" +
	"\x15CARD_BRAND_MASTERCARD\x10\x02\x12\x1f\n" +
	"\x1bCARD_BRAND_AMERICAN_EXPRESS\x10\x03\x12\x17\n" +
	"\x13CARD_BRAND_DISCOVER\x10\x04\x12\x1a\n" +
	"\x16CARD_BRAND_DINERS_CLUB\x10\x05\x12\x12\n" +
	"\x0eCARD_BRAND_JCB\x10\x06\x12\x17\n" +
	"\x13CARD_BRAND_UNIONPAY\x10\a*t\n" +
	"\n" +
	"CardStatus\x12\x1b\n" +
	"\x17CARD_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CARD_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12CARD_STATUS_ACTIVE\x10\x02\x12\x18\n" +
	"\x14CARD_STATUS_INACTIVE\x10\x032\xbf\x02\n" +
	"\vCardService\x12I\n" +
	"\n" +
	"CreateCard\x12\x1b.payments.CreateCardRequest\x1a\x1c.payments.CreateCardResponse\"\x00\x12I\n" +
	"\n" +
	"DeleteCard\x12\x1b.payments.DeleteCardRequest\x1a\x1c.payments.DeleteCardResponse\"\x00\x12C\n" +
	"\bGetCards\x12\x19.payments.GetCardsRequest\x1a\x1a.payments.GetCardsResponse\"\x00\x12U\n" +
	"\x0eSetDefaultCard\x12\x1f.payments.SetDefaultCardRequest\x1a .payments.SetDefaultCardResponse\"\x00BMZKgithub.com/cinchprotocol/cinch-api/packages/proto/pkg/proto/assets/paymentsb\x06proto3"

var (
	file_assets_payments_cards_proto_rawDescOnce sync.Once
	file_assets_payments_cards_proto_rawDescData []byte
)

func file_assets_payments_cards_proto_rawDescGZIP() []byte {
	file_assets_payments_cards_proto_rawDescOnce.Do(func() {
		file_assets_payments_cards_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assets_payments_cards_proto_rawDesc), len(file_assets_payments_cards_proto_rawDesc)))
	})
	return file_assets_payments_cards_proto_rawDescData
}

var file_assets_payments_cards_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_assets_payments_cards_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_assets_payments_cards_proto_goTypes = []any{
	(CardBrand)(0),                 // 0: payments.CardBrand
	(CardStatus)(0),                // 1: payments.CardStatus
	(*Card)(nil),                   // 2: payments.Card
	(*CreateCardRequest)(nil),      // 3: payments.CreateCardRequest
	(*CreateCardResponse)(nil),     // 4: payments.CreateCardResponse
	(*DeleteCardRequest)(nil),      // 5: payments.DeleteCardRequest
	(*DeleteCardResponse)(nil),     // 6: payments.DeleteCardResponse
	(*GetCardsRequest)(nil),        // 7: payments.GetCardsRequest
	(*GetCardsResponse)(nil),       // 8: payments.GetCardsResponse
	(*SetDefaultCardRequest)(nil),  // 9: payments.SetDefaultCardRequest
	(*SetDefaultCardResponse)(nil), // 10: payments.SetDefaultCardResponse
}
var file_assets_payments_cards_proto_depIdxs = []int32{
	0,  // 0: payments.Card.brand:type_name -> payments.CardBrand
	1,  // 1: payments.Card.status:type_name -> payments.CardStatus
	2,  // 2: payments.CreateCardResponse.card:type_name -> payments.Card
	2,  // 3: payments.GetCardsResponse.cards:type_name -> payments.Card
	3,  // 4: payments.CardService.CreateCard:input_type -> payments.CreateCardRequest
	5,  // 5: payments.CardService.DeleteCard:input_type -> payments.DeleteCardRequest
	7,  // 6: payments.CardService.GetCards:input_type -> payments.GetCardsRequest
	9,  // 7: payments.CardService.SetDefaultCard:input_type -> payments.SetDefaultCardRequest
	4,  // 8: payments.CardService.CreateCard:output_type -> payments.CreateCardResponse
	6,  // 9: payments.CardService.DeleteCard:output_type -> payments.DeleteCardResponse
	8,  // 10: payments.CardService.GetCards:output_type -> payments.GetCardsResponse
	10, // 11: payments.CardService.SetDefaultCard:output_type -> payments.SetDefaultCardResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_assets_payments_cards_proto_init() }
func file_assets_payments_cards_proto_init() {
	if File_assets_payments_cards_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assets_payments_cards_proto_rawDesc), len(file_assets_payments_cards_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assets_payments_cards_proto_goTypes,
		DependencyIndexes: file_assets_payments_cards_proto_depIdxs,
		EnumInfos:         file_assets_payments_cards_proto_enumTypes,
		MessageInfos:      file_assets_payments_cards_proto_msgTypes,
	}.Build()
	File_assets_payments_cards_proto = out.File
	file_assets_payments_cards_proto_goTypes = nil
	file_assets_payments_cards_proto_depIdxs = nil
}
