// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: billing/invoices.proto

package billing

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Invoice model for responses
type Invoice struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId      string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	TotalAmount    float64                `protobuf:"fixed64,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	IssuedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	DueAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=due_at,json=dueAt,proto3" json:"due_at,omitempty"`
	PaidAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_billing_invoices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_billing_invoices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_billing_invoices_proto_rawDescGZIP(), []int{0}
}

func (x *Invoice) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *Invoice) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *Invoice) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Invoice) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Invoice) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *Invoice) GetDueAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DueAt
	}
	return nil
}

func (x *Invoice) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

func (x *Invoice) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Invoice) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// List invoices
type ListInvoicesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListInvoicesRequest) Reset() {
	*x = ListInvoicesRequest{}
	mi := &file_billing_invoices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoicesRequest) ProtoMessage() {}

func (x *ListInvoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_invoices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoicesRequest.ProtoReflect.Descriptor instead.
func (*ListInvoicesRequest) Descriptor() ([]byte, []int) {
	return file_billing_invoices_proto_rawDescGZIP(), []int{1}
}

func (x *ListInvoicesRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type ListInvoicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoices      []*Invoice             `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoicesResponse) Reset() {
	*x = ListInvoicesResponse{}
	mi := &file_billing_invoices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoicesResponse) ProtoMessage() {}

func (x *ListInvoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_invoices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoicesResponse.ProtoReflect.Descriptor instead.
func (*ListInvoicesResponse) Descriptor() ([]byte, []int) {
	return file_billing_invoices_proto_rawDescGZIP(), []int{2}
}

func (x *ListInvoicesResponse) GetInvoices() []*Invoice {
	if x != nil {
		return x.Invoices
	}
	return nil
}

// Generate invoice
type GenerateInvoiceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateInvoiceRequest) Reset() {
	*x = GenerateInvoiceRequest{}
	mi := &file_billing_invoices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInvoiceRequest) ProtoMessage() {}

func (x *GenerateInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_invoices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GenerateInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_billing_invoices_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateInvoiceRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type GenerateInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateInvoiceResponse) Reset() {
	*x = GenerateInvoiceResponse{}
	mi := &file_billing_invoices_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInvoiceResponse) ProtoMessage() {}

func (x *GenerateInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_invoices_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInvoiceResponse.ProtoReflect.Descriptor instead.
func (*GenerateInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_billing_invoices_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateInvoiceResponse) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *GenerateInvoiceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GenerateInvoiceResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Get invoice
type GetInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceRequest) Reset() {
	*x = GetInvoiceRequest{}
	mi := &file_billing_invoices_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceRequest) ProtoMessage() {}

func (x *GetInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_invoices_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GetInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_billing_invoices_proto_rawDescGZIP(), []int{5}
}

func (x *GetInvoiceRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

type GetInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *Invoice               `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceResponse) Reset() {
	*x = GetInvoiceResponse{}
	mi := &file_billing_invoices_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceResponse) ProtoMessage() {}

func (x *GetInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_invoices_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceResponse.ProtoReflect.Descriptor instead.
func (*GetInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_billing_invoices_proto_rawDescGZIP(), []int{6}
}

func (x *GetInvoiceResponse) GetInvoice() *Invoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

// Mark invoice as paid
type MarkInvoiceAsPaidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkInvoiceAsPaidRequest) Reset() {
	*x = MarkInvoiceAsPaidRequest{}
	mi := &file_billing_invoices_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkInvoiceAsPaidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkInvoiceAsPaidRequest) ProtoMessage() {}

func (x *MarkInvoiceAsPaidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_invoices_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkInvoiceAsPaidRequest.ProtoReflect.Descriptor instead.
func (*MarkInvoiceAsPaidRequest) Descriptor() ([]byte, []int) {
	return file_billing_invoices_proto_rawDescGZIP(), []int{7}
}

func (x *MarkInvoiceAsPaidRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

type MarkInvoiceAsPaidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PaidAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkInvoiceAsPaidResponse) Reset() {
	*x = MarkInvoiceAsPaidResponse{}
	mi := &file_billing_invoices_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkInvoiceAsPaidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkInvoiceAsPaidResponse) ProtoMessage() {}

func (x *MarkInvoiceAsPaidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_invoices_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkInvoiceAsPaidResponse.ProtoReflect.Descriptor instead.
func (*MarkInvoiceAsPaidResponse) Descriptor() ([]byte, []int) {
	return file_billing_invoices_proto_rawDescGZIP(), []int{8}
}

func (x *MarkInvoiceAsPaidResponse) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *MarkInvoiceAsPaidResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MarkInvoiceAsPaidResponse) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

// List invoice line items
type ListInvoiceLineItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoiceLineItemsRequest) Reset() {
	*x = ListInvoiceLineItemsRequest{}
	mi := &file_billing_invoices_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoiceLineItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoiceLineItemsRequest) ProtoMessage() {}

func (x *ListInvoiceLineItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_invoices_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoiceLineItemsRequest.ProtoReflect.Descriptor instead.
func (*ListInvoiceLineItemsRequest) Descriptor() ([]byte, []int) {
	return file_billing_invoices_proto_rawDescGZIP(), []int{9}
}

func (x *ListInvoiceLineItemsRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

type ListInvoiceLineItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineItems     []*InvoiceLineItem     `protobuf:"bytes,1,rep,name=line_items,json=lineItems,proto3" json:"line_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoiceLineItemsResponse) Reset() {
	*x = ListInvoiceLineItemsResponse{}
	mi := &file_billing_invoices_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoiceLineItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoiceLineItemsResponse) ProtoMessage() {}

func (x *ListInvoiceLineItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_invoices_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoiceLineItemsResponse.ProtoReflect.Descriptor instead.
func (*ListInvoiceLineItemsResponse) Descriptor() ([]byte, []int) {
	return file_billing_invoices_proto_rawDescGZIP(), []int{10}
}

func (x *ListInvoiceLineItemsResponse) GetLineItems() []*InvoiceLineItem {
	if x != nil {
		return x.LineItems
	}
	return nil
}

var File_billing_invoices_proto protoreflect.FileDescriptor

const file_billing_invoices_proto_rawDesc = "" +
	"\n" +
	"\x16billing/invoices.proto\x12\abilling\x1a\x14billing/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa3\x03\n" +
	"\aInvoice\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x01R\vtotalAmount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x127\n" +
	"\tissued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x121\n" +
	"\x06due_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05dueAt\x123\n" +
	"\apaid_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\">\n" +
	"\x13ListInvoicesRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"D\n" +
	"\x14ListInvoicesResponse\x12,\n" +
	"\binvoices\x18\x01 \x03(\v2\x10.billing.InvoiceR\binvoices\"A\n" +
	"\x16GenerateInvoiceRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"\x8b\x01\n" +
	"\x17GenerateInvoiceResponse\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"2\n" +
	"\x11GetInvoiceRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\"@\n" +
	"\x12GetInvoiceResponse\x12*\n" +
	"\ainvoice\x18\x01 \x01(\v2\x10.billing.InvoiceR\ainvoice\"9\n" +
	"\x18MarkInvoiceAsPaidRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\"\x87\x01\n" +
	"\x19MarkInvoiceAsPaidResponse\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x123\n" +
	"\apaid_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\"<\n" +
	"\x1bListInvoiceLineItemsRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\"W\n" +
	"\x1cListInvoiceLineItemsResponse\x127\n" +
	"\n" +
	"line_items\x18\x01 \x03(\v2\x18.billing.InvoiceLineItemR\tlineItems2\xaa\x05\n" +
	"\x0fInvoicesService\x12\x81\x01\n" +
	"\fListInvoices\x12\x1c.billing.ListInvoicesRequest\x1a\x1d.billing.ListInvoicesResponse\"4\x82\xd3\xe4\x93\x02.\x12,/v1/subscriptions/{subscription_id}/invoices\x12\x8d\x01\n" +
	"\x0fGenerateInvoice\x12\x1f.billing.GenerateInvoiceRequest\x1a .billing.GenerateInvoiceResponse\"7\x82\xd3\xe4\x93\x021:\x01*\",/v1/subscriptions/{subscription_id}/invoices\x12h\n" +
	"\n" +
	"GetInvoice\x12\x1a.billing.GetInvoiceRequest\x1a\x1b.billing.GetInvoiceResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/invoices/{invoice_id}\x12\x84\x01\n" +
	"\x11MarkInvoiceAsPaid\x12!.billing.MarkInvoiceAsPaidRequest\x1a\".billing.MarkInvoiceAsPaidResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\x1a\x1d/v1/invoices/{invoice_id}/pay\x12\x91\x01\n" +
	"\x14ListInvoiceLineItems\x12$.billing.ListInvoiceLineItemsRequest\x1a%.billing.ListInvoiceLineItemsResponse\",\x82\xd3\xe4\x93\x02&\x12$/v1/invoices/{invoice_id}/line_itemsB\xbc\x01\x92A+\x12)\n" +
	"\fInvoices API\x12\x14Invoices service API2\x031.0\n" +
	"\vcom.billingB\rInvoicesProtoP\x01Z4github.com/sundowndev/grpc-api-example/proto/billing\xa2\x02\x03BXX\xaa\x02\aBilling\xca\x02\aBilling\xe2\x02\x13Billing\\GPBMetadata\xea\x02\aBillingb\x06proto3"

var (
	file_billing_invoices_proto_rawDescOnce sync.Once
	file_billing_invoices_proto_rawDescData []byte
)

func file_billing_invoices_proto_rawDescGZIP() []byte {
	file_billing_invoices_proto_rawDescOnce.Do(func() {
		file_billing_invoices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_invoices_proto_rawDesc), len(file_billing_invoices_proto_rawDesc)))
	})
	return file_billing_invoices_proto_rawDescData
}

var file_billing_invoices_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_billing_invoices_proto_goTypes = []any{
	(*Invoice)(nil),                      // 0: billing.Invoice
	(*ListInvoicesRequest)(nil),          // 1: billing.ListInvoicesRequest
	(*ListInvoicesResponse)(nil),         // 2: billing.ListInvoicesResponse
	(*GenerateInvoiceRequest)(nil),       // 3: billing.GenerateInvoiceRequest
	(*GenerateInvoiceResponse)(nil),      // 4: billing.GenerateInvoiceResponse
	(*GetInvoiceRequest)(nil),            // 5: billing.GetInvoiceRequest
	(*GetInvoiceResponse)(nil),           // 6: billing.GetInvoiceResponse
	(*MarkInvoiceAsPaidRequest)(nil),     // 7: billing.MarkInvoiceAsPaidRequest
	(*MarkInvoiceAsPaidResponse)(nil),    // 8: billing.MarkInvoiceAsPaidResponse
	(*ListInvoiceLineItemsRequest)(nil),  // 9: billing.ListInvoiceLineItemsRequest
	(*ListInvoiceLineItemsResponse)(nil), // 10: billing.ListInvoiceLineItemsResponse
	(*timestamppb.Timestamp)(nil),        // 11: google.protobuf.Timestamp
	(*InvoiceLineItem)(nil),              // 12: billing.InvoiceLineItem
}
var file_billing_invoices_proto_depIdxs = []int32{
	11, // 0: billing.Invoice.issued_at:type_name -> google.protobuf.Timestamp
	11, // 1: billing.Invoice.due_at:type_name -> google.protobuf.Timestamp
	11, // 2: billing.Invoice.paid_at:type_name -> google.protobuf.Timestamp
	11, // 3: billing.Invoice.created_at:type_name -> google.protobuf.Timestamp
	11, // 4: billing.Invoice.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: billing.ListInvoicesResponse.invoices:type_name -> billing.Invoice
	11, // 6: billing.GenerateInvoiceResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 7: billing.GetInvoiceResponse.invoice:type_name -> billing.Invoice
	11, // 8: billing.MarkInvoiceAsPaidResponse.paid_at:type_name -> google.protobuf.Timestamp
	12, // 9: billing.ListInvoiceLineItemsResponse.line_items:type_name -> billing.InvoiceLineItem
	1,  // 10: billing.InvoicesService.ListInvoices:input_type -> billing.ListInvoicesRequest
	3,  // 11: billing.InvoicesService.GenerateInvoice:input_type -> billing.GenerateInvoiceRequest
	5,  // 12: billing.InvoicesService.GetInvoice:input_type -> billing.GetInvoiceRequest
	7,  // 13: billing.InvoicesService.MarkInvoiceAsPaid:input_type -> billing.MarkInvoiceAsPaidRequest
	9,  // 14: billing.InvoicesService.ListInvoiceLineItems:input_type -> billing.ListInvoiceLineItemsRequest
	2,  // 15: billing.InvoicesService.ListInvoices:output_type -> billing.ListInvoicesResponse
	4,  // 16: billing.InvoicesService.GenerateInvoice:output_type -> billing.GenerateInvoiceResponse
	6,  // 17: billing.InvoicesService.GetInvoice:output_type -> billing.GetInvoiceResponse
	8,  // 18: billing.InvoicesService.MarkInvoiceAsPaid:output_type -> billing.MarkInvoiceAsPaidResponse
	10, // 19: billing.InvoicesService.ListInvoiceLineItems:output_type -> billing.ListInvoiceLineItemsResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_billing_invoices_proto_init() }
func file_billing_invoices_proto_init() {
	if File_billing_invoices_proto != nil {
		return
	}
	file_billing_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_invoices_proto_rawDesc), len(file_billing_invoices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_invoices_proto_goTypes,
		DependencyIndexes: file_billing_invoices_proto_depIdxs,
		MessageInfos:      file_billing_invoices_proto_msgTypes,
	}.Build()
	File_billing_invoices_proto = out.File
	file_billing_invoices_proto_goTypes = nil
	file_billing_invoices_proto_depIdxs = nil
}
