// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: cart/cart.proto

package cart

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Health check messages
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_cart_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_cart_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Create payment messages
type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_cart_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePaymentRequest) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_cart_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

// Update payment messages
type UpdatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Payment       *Payment               `protobuf:"bytes,2,opt,name=payment,proto3" json:"payment,omitempty"`
	Webhook       *Webhook               `protobuf:"bytes,3,opt,name=webhook,proto3" json:"webhook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentRequest) Reset() {
	*x = UpdatePaymentRequest{}
	mi := &file_cart_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentRequest) ProtoMessage() {}

func (x *UpdatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *UpdatePaymentRequest) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *UpdatePaymentRequest) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

type UpdatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentResponse) Reset() {
	*x = UpdatePaymentResponse{}
	mi := &file_cart_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentResponse) ProtoMessage() {}

func (x *UpdatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentResponse.ProtoReflect.Descriptor instead.
func (*UpdatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

// Create refund messages
type CreateRefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"` // Original payment
	Refund        *Refund                `protobuf:"bytes,2,opt,name=refund,proto3" json:"refund,omitempty"`   // New refund to create
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRefundRequest) Reset() {
	*x = CreateRefundRequest{}
	mi := &file_cart_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRefundRequest) ProtoMessage() {}

func (x *CreateRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRefundRequest.ProtoReflect.Descriptor instead.
func (*CreateRefundRequest) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRefundRequest) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *CreateRefundRequest) GetRefund() *Refund {
	if x != nil {
		return x.Refund
	}
	return nil
}

type CreateRefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refund        *Refund                `protobuf:"bytes,1,opt,name=refund,proto3" json:"refund,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRefundResponse) Reset() {
	*x = CreateRefundResponse{}
	mi := &file_cart_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRefundResponse) ProtoMessage() {}

func (x *CreateRefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRefundResponse.ProtoReflect.Descriptor instead.
func (*CreateRefundResponse) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRefundResponse) GetRefund() *Refund {
	if x != nil {
		return x.Refund
	}
	return nil
}

// Update refund messages
type UpdateRefundRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RefundId        string                 `protobuf:"bytes,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	PartnerRefundId string                 `protobuf:"bytes,2,opt,name=partner_refund_id,json=partnerRefundId,proto3" json:"partner_refund_id,omitempty"` // Stripe refund ID
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	EventType       string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`                                                        // Type of webhook event
	EventId         string                 `protobuf:"bytes,5,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`                                                              // Stripe event ID
	Metadata        map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional event metadata
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateRefundRequest) Reset() {
	*x = UpdateRefundRequest{}
	mi := &file_cart_cart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRefundRequest) ProtoMessage() {}

func (x *UpdateRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRefundRequest.ProtoReflect.Descriptor instead.
func (*UpdateRefundRequest) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRefundRequest) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *UpdateRefundRequest) GetPartnerRefundId() string {
	if x != nil {
		return x.PartnerRefundId
	}
	return ""
}

func (x *UpdateRefundRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateRefundRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *UpdateRefundRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpdateRefundRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UpdateRefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refund        *Refund                `protobuf:"bytes,1,opt,name=refund,proto3" json:"refund,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRefundResponse) Reset() {
	*x = UpdateRefundResponse{}
	mi := &file_cart_cart_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRefundResponse) ProtoMessage() {}

func (x *UpdateRefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRefundResponse.ProtoReflect.Descriptor instead.
func (*UpdateRefundResponse) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRefundResponse) GetRefund() *Refund {
	if x != nil {
		return x.Refund
	}
	return nil
}

// GetPaymentMethodRequest is the request for getting a payment method
type GetPaymentMethodRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethodCode string                 `protobuf:"bytes,1,opt,name=payment_method_code,json=paymentMethodCode,proto3" json:"payment_method_code,omitempty"` // VARCHAR(70)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetPaymentMethodRequest) Reset() {
	*x = GetPaymentMethodRequest{}
	mi := &file_cart_cart_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentMethodRequest) ProtoMessage() {}

func (x *GetPaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{10}
}

func (x *GetPaymentMethodRequest) GetPaymentMethodCode() string {
	if x != nil {
		return x.PaymentMethodCode
	}
	return ""
}

// GetPaymentMethodResponse is the response for getting a payment method
type GetPaymentMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethod *PaymentMethod         `protobuf:"bytes,1,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentMethodResponse) Reset() {
	*x = GetPaymentMethodResponse{}
	mi := &file_cart_cart_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentMethodResponse) ProtoMessage() {}

func (x *GetPaymentMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentMethodResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentMethodResponse) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{11}
}

func (x *GetPaymentMethodResponse) GetPaymentMethod() *PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

// ListPaymentMethodsRequest is the request for listing payment methods
type ListPaymentMethodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentMethodsRequest) Reset() {
	*x = ListPaymentMethodsRequest{}
	mi := &file_cart_cart_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentMethodsRequest) ProtoMessage() {}

func (x *ListPaymentMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentMethodsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentMethodsRequest) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{12}
}

// ListPaymentMethodsResponse is the response for listing payment methods
type ListPaymentMethodsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethods []*PaymentMethod       `protobuf:"bytes,1,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListPaymentMethodsResponse) Reset() {
	*x = ListPaymentMethodsResponse{}
	mi := &file_cart_cart_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentMethodsResponse) ProtoMessage() {}

func (x *ListPaymentMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentMethodsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentMethodsResponse) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{13}
}

func (x *ListPaymentMethodsResponse) GetPaymentMethods() []*PaymentMethod {
	if x != nil {
		return x.PaymentMethods
	}
	return nil
}

// PaymentMethod represents a payment method in the system
type PaymentMethod struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                          // BINARY(16)
	PaymentMethodCode string                 `protobuf:"bytes,2,opt,name=payment_method_code,json=paymentMethodCode,proto3" json:"payment_method_code,omitempty"` // VARCHAR(70)
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                      // VARCHAR(255)
	Description       string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                                        // TEXT
	Status            string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                                  // ENUM('active', 'inactive')
	CreatedAt         string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                           // DATETIME
	UpdatedAt         string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                           // DATETIME
	DeletedAt         string                 `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`                           // DATETIME
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PaymentMethod) Reset() {
	*x = PaymentMethod{}
	mi := &file_cart_cart_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethod) ProtoMessage() {}

func (x *PaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethod.ProtoReflect.Descriptor instead.
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{14}
}

func (x *PaymentMethod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentMethod) GetPaymentMethodCode() string {
	if x != nil {
		return x.PaymentMethodCode
	}
	return ""
}

func (x *PaymentMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PaymentMethod) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PaymentMethod) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentMethod) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PaymentMethod) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *PaymentMethod) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

// Refund represents a refund in the system
type Refund struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO 8601 date string
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // ISO 8601 date string
	Attempts      []*RefundAttempt       `protobuf:"bytes,8,rep,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Refund) Reset() {
	*x = Refund{}
	mi := &file_cart_cart_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refund) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refund) ProtoMessage() {}

func (x *Refund) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refund.ProtoReflect.Descriptor instead.
func (*Refund) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{15}
}

func (x *Refund) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Refund) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Refund) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Refund) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Refund) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Refund) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Refund) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Refund) GetAttempts() []*RefundAttempt {
	if x != nil {
		return x.Attempts
	}
	return nil
}

// RefundAttempt represents a refund attempt in the system
type RefundAttempt struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RefundId        string                 `protobuf:"bytes,2,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	PartnerId       string                 `protobuf:"bytes,3,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	PartnerRefundId string                 `protobuf:"bytes,5,opt,name=partner_refund_id,json=partnerRefundId,proto3" json:"partner_refund_id,omitempty"` // Stripe refund ID
	ErrorMessage    string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`            // Optional error message if processing failed
	CreatedAt       string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                     // ISO 8601 date string
	UpdatedAt       string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                     // ISO 8601 date string
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RefundAttempt) Reset() {
	*x = RefundAttempt{}
	mi := &file_cart_cart_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundAttempt) ProtoMessage() {}

func (x *RefundAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundAttempt.ProtoReflect.Descriptor instead.
func (*RefundAttempt) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{16}
}

func (x *RefundAttempt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RefundAttempt) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *RefundAttempt) GetPartnerId() string {
	if x != nil {
		return x.PartnerId
	}
	return ""
}

func (x *RefundAttempt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RefundAttempt) GetPartnerRefundId() string {
	if x != nil {
		return x.PartnerRefundId
	}
	return ""
}

func (x *RefundAttempt) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RefundAttempt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RefundAttempt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Payment represents a payment in the system
type Payment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                    // BINARY(16)
	PaymentMethodId string                 `protobuf:"bytes,2,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"` // BINARY(16)
	InvoiceId       string                 `protobuf:"bytes,3,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`                     // BINARY(16)
	Amount          float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`                                          // NUMERIC(12,2)
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                            // ENUM('pending', 'paid', 'failed', 'partially_refunded', 'refunded')
	DueOn           string                 `protobuf:"bytes,6,opt,name=due_on,json=dueOn,proto3" json:"due_on,omitempty"`                                 // DATETIME
	PaidAt          string                 `protobuf:"bytes,7,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`                              // DATETIME
	CreatedAt       string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                     // DATETIME
	UpdatedAt       string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                     // DATETIME
	Attempts        []*PaymentAttempt      `protobuf:"bytes,10,rep,name=attempts,proto3" json:"attempts,omitempty"`
	Refunds         []*Refund              `protobuf:"bytes,11,rep,name=refunds,proto3" json:"refunds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_cart_cart_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{17}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *Payment) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetDueOn() string {
	if x != nil {
		return x.DueOn
	}
	return ""
}

func (x *Payment) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

func (x *Payment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Payment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Payment) GetAttempts() []*PaymentAttempt {
	if x != nil {
		return x.Attempts
	}
	return nil
}

func (x *Payment) GetRefunds() []*Refund {
	if x != nil {
		return x.Refunds
	}
	return nil
}

// PaymentAttempt represents a payment attempt in the system
type PaymentAttempt struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                       // BINARY(16)
	PaymentId        string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`                        // BINARY(16)
	PaymentMethodId  string                 `protobuf:"bytes,3,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`    // BINARY(16)
	PartnerId        string                 `protobuf:"bytes,4,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`                        // BINARY(16)
	PartnerCode      string                 `protobuf:"bytes,5,opt,name=partner_code,json=partnerCode,proto3" json:"partner_code,omitempty"`                  // VARCHAR(70)
	Status           string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                               // ENUM('pending', 'paid', 'failed', 'partially_refunded', 'refunded')
	PartnerPaymentId string                 `protobuf:"bytes,7,opt,name=partner_payment_id,json=partnerPaymentId,proto3" json:"partner_payment_id,omitempty"` // Stripe payment ID
	RedirectUrl      string                 `protobuf:"bytes,8,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`                  // Optional URL for redirect-based payment flows
	ErrorMessage     string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`               // Optional error message if processing failed
	CreatedAt        string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                       // DATETIME
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PaymentAttempt) Reset() {
	*x = PaymentAttempt{}
	mi := &file_cart_cart_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentAttempt) ProtoMessage() {}

func (x *PaymentAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentAttempt.ProtoReflect.Descriptor instead.
func (*PaymentAttempt) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{18}
}

func (x *PaymentAttempt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentAttempt) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentAttempt) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *PaymentAttempt) GetPartnerId() string {
	if x != nil {
		return x.PartnerId
	}
	return ""
}

func (x *PaymentAttempt) GetPartnerCode() string {
	if x != nil {
		return x.PartnerCode
	}
	return ""
}

func (x *PaymentAttempt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentAttempt) GetPartnerPaymentId() string {
	if x != nil {
		return x.PartnerPaymentId
	}
	return ""
}

func (x *PaymentAttempt) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *PaymentAttempt) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PaymentAttempt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// EnablePaymentMethodRequest is the request for enabling a payment method
type EnablePaymentMethodRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethodCode string                 `protobuf:"bytes,1,opt,name=payment_method_code,json=paymentMethodCode,proto3" json:"payment_method_code,omitempty"` // VARCHAR(70)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EnablePaymentMethodRequest) Reset() {
	*x = EnablePaymentMethodRequest{}
	mi := &file_cart_cart_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnablePaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnablePaymentMethodRequest) ProtoMessage() {}

func (x *EnablePaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnablePaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*EnablePaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{19}
}

func (x *EnablePaymentMethodRequest) GetPaymentMethodCode() string {
	if x != nil {
		return x.PaymentMethodCode
	}
	return ""
}

// EnablePaymentMethodResponse is the response for enabling a payment method
type EnablePaymentMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnablePaymentMethodResponse) Reset() {
	*x = EnablePaymentMethodResponse{}
	mi := &file_cart_cart_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnablePaymentMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnablePaymentMethodResponse) ProtoMessage() {}

func (x *EnablePaymentMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnablePaymentMethodResponse.ProtoReflect.Descriptor instead.
func (*EnablePaymentMethodResponse) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{20}
}

// DisablePaymentMethodRequest is the request for disabling a payment method
type DisablePaymentMethodRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethodCode string                 `protobuf:"bytes,1,opt,name=payment_method_code,json=paymentMethodCode,proto3" json:"payment_method_code,omitempty"` // VARCHAR(70)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DisablePaymentMethodRequest) Reset() {
	*x = DisablePaymentMethodRequest{}
	mi := &file_cart_cart_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisablePaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisablePaymentMethodRequest) ProtoMessage() {}

func (x *DisablePaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisablePaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*DisablePaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{21}
}

func (x *DisablePaymentMethodRequest) GetPaymentMethodCode() string {
	if x != nil {
		return x.PaymentMethodCode
	}
	return ""
}

// DisablePaymentMethodResponse is the response for disabling a payment method
type DisablePaymentMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisablePaymentMethodResponse) Reset() {
	*x = DisablePaymentMethodResponse{}
	mi := &file_cart_cart_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisablePaymentMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisablePaymentMethodResponse) ProtoMessage() {}

func (x *DisablePaymentMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisablePaymentMethodResponse.ProtoReflect.Descriptor instead.
func (*DisablePaymentMethodResponse) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{22}
}

// DeletePaymentMethodRequest is the request for deleting a payment method
type DeletePaymentMethodRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethodCode string                 `protobuf:"bytes,1,opt,name=payment_method_code,json=paymentMethodCode,proto3" json:"payment_method_code,omitempty"` // VARCHAR(70)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeletePaymentMethodRequest) Reset() {
	*x = DeletePaymentMethodRequest{}
	mi := &file_cart_cart_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaymentMethodRequest) ProtoMessage() {}

func (x *DeletePaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*DeletePaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{23}
}

func (x *DeletePaymentMethodRequest) GetPaymentMethodCode() string {
	if x != nil {
		return x.PaymentMethodCode
	}
	return ""
}

// DeletePaymentMethodResponse is the response for deleting a payment method
type DeletePaymentMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePaymentMethodResponse) Reset() {
	*x = DeletePaymentMethodResponse{}
	mi := &file_cart_cart_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePaymentMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaymentMethodResponse) ProtoMessage() {}

func (x *DeletePaymentMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaymentMethodResponse.ProtoReflect.Descriptor instead.
func (*DeletePaymentMethodResponse) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{24}
}

// Webhook represents a webhook event in the system
type Webhook struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PartnerPaymentId string                 `protobuf:"bytes,2,opt,name=partner_payment_id,json=partnerPaymentId,proto3" json:"partner_payment_id,omitempty"`
	PartnerEventType string                 `protobuf:"bytes,3,opt,name=partner_event_type,json=partnerEventType,proto3" json:"partner_event_type,omitempty"`
	PartnerWebhookId string                 `protobuf:"bytes,4,opt,name=partner_webhook_id,json=partnerWebhookId,proto3" json:"partner_webhook_id,omitempty"`
	Method           string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Url              string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Headers          []byte                 `protobuf:"bytes,7,opt,name=headers,proto3" json:"headers,omitempty"`
	Payload          []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Webhook) Reset() {
	*x = Webhook{}
	mi := &file_cart_cart_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webhook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webhook) ProtoMessage() {}

func (x *Webhook) ProtoReflect() protoreflect.Message {
	mi := &file_cart_cart_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Webhook.ProtoReflect.Descriptor instead.
func (*Webhook) Descriptor() ([]byte, []int) {
	return file_cart_cart_proto_rawDescGZIP(), []int{25}
}

func (x *Webhook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Webhook) GetPartnerPaymentId() string {
	if x != nil {
		return x.PartnerPaymentId
	}
	return ""
}

func (x *Webhook) GetPartnerEventType() string {
	if x != nil {
		return x.PartnerEventType
	}
	return ""
}

func (x *Webhook) GetPartnerWebhookId() string {
	if x != nil {
		return x.PartnerWebhookId
	}
	return ""
}

func (x *Webhook) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Webhook) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Webhook) GetHeaders() []byte {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Webhook) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_cart_cart_proto protoreflect.FileDescriptor

const file_cart_cart_proto_rawDesc = "" +
	"\n" +
	"\x0fcart/cart.proto\x12\x04cart\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"?\n" +
	"\x14CreatePaymentRequest\x12'\n" +
	"\apayment\x18\x01 \x01(\v2\r.cart.PaymentR\apayment\"@\n" +
	"\x15CreatePaymentResponse\x12'\n" +
	"\apayment\x18\x01 \x01(\v2\r.cart.PaymentR\apayment\"\x87\x01\n" +
	"\x14UpdatePaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12'\n" +
	"\apayment\x18\x02 \x01(\v2\r.cart.PaymentR\apayment\x12'\n" +
	"\awebhook\x18\x03 \x01(\v2\r.cart.WebhookR\awebhook\"@\n" +
	"\x15UpdatePaymentResponse\x12'\n" +
	"\apayment\x18\x01 \x01(\v2\r.cart.PaymentR\apayment\"d\n" +
	"\x13CreateRefundRequest\x12'\n" +
	"\apayment\x18\x01 \x01(\v2\r.cart.PaymentR\apayment\x12$\n" +
	"\x06refund\x18\x02 \x01(\v2\f.cart.RefundR\x06refund\"<\n" +
	"\x14CreateRefundResponse\x12$\n" +
	"\x06refund\x18\x01 \x01(\v2\f.cart.RefundR\x06refund\"\xb2\x02\n" +
	"\x13UpdateRefundRequest\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\tR\brefundId\x12*\n" +
	"\x11partner_refund_id\x18\x02 \x01(\tR\x0fpartnerRefundId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x19\n" +
	"\bevent_id\x18\x05 \x01(\tR\aeventId\x12C\n" +
	"\bmetadata\x18\x06 \x03(\v2'.cart.UpdateRefundRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x14UpdateRefundResponse\x12$\n" +
	"\x06refund\x18\x01 \x01(\v2\f.cart.RefundR\x06refund\"I\n" +
	"\x17GetPaymentMethodRequest\x12.\n" +
	"\x13payment_method_code\x18\x01 \x01(\tR\x11paymentMethodCode\"V\n" +
	"\x18GetPaymentMethodResponse\x12:\n" +
	"\x0epayment_method\x18\x01 \x01(\v2\x13.cart.PaymentMethodR\rpaymentMethod\"\x1b\n" +
	"\x19ListPaymentMethodsRequest\"Z\n" +
	"\x1aListPaymentMethodsResponse\x12<\n" +
	"\x0fpayment_methods\x18\x01 \x03(\v2\x13.cart.PaymentMethodR\x0epaymentMethods\"\xfa\x01\n" +
	"\rPaymentMethod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x13payment_method_code\x18\x02 \x01(\tR\x11paymentMethodCode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\b \x01(\tR\tdeletedAt\"\xee\x01\n" +
	"\x06Refund\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12/\n" +
	"\battempts\x18\b \x03(\v2\x13.cart.RefundAttemptR\battempts\"\x82\x02\n" +
	"\rRefundAttempt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trefund_id\x18\x02 \x01(\tR\brefundId\x12\x1d\n" +
	"\n" +
	"partner_id\x18\x03 \x01(\tR\tpartnerId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12*\n" +
	"\x11partner_refund_id\x18\x05 \x01(\tR\x0fpartnerRefundId\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\xdc\x02\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11payment_method_id\x18\x02 \x01(\tR\x0fpaymentMethodId\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x03 \x01(\tR\tinvoiceId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x15\n" +
	"\x06due_on\x18\x06 \x01(\tR\x05dueOn\x12\x17\n" +
	"\apaid_at\x18\a \x01(\tR\x06paidAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x120\n" +
	"\battempts\x18\n" +
	" \x03(\v2\x14.cart.PaymentAttemptR\battempts\x12&\n" +
	"\arefunds\x18\v \x03(\v2\f.cart.RefundR\arefunds\"\xda\x02\n" +
	"\x0ePaymentAttempt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12*\n" +
	"\x11payment_method_id\x18\x03 \x01(\tR\x0fpaymentMethodId\x12\x1d\n" +
	"\n" +
	"partner_id\x18\x04 \x01(\tR\tpartnerId\x12!\n" +
	"\fpartner_code\x18\x05 \x01(\tR\vpartnerCode\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12,\n" +
	"\x12partner_payment_id\x18\a \x01(\tR\x10partnerPaymentId\x12!\n" +
	"\fredirect_url\x18\b \x01(\tR\vredirectUrl\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"L\n" +
	"\x1aEnablePaymentMethodRequest\x12.\n" +
	"\x13payment_method_code\x18\x01 \x01(\tR\x11paymentMethodCode\"\x1d\n" +
	"\x1bEnablePaymentMethodResponse\"M\n" +
	"\x1bDisablePaymentMethodRequest\x12.\n" +
	"\x13payment_method_code\x18\x01 \x01(\tR\x11paymentMethodCode\"\x1e\n" +
	"\x1cDisablePaymentMethodResponse\"L\n" +
	"\x1aDeletePaymentMethodRequest\x12.\n" +
	"\x13payment_method_code\x18\x01 \x01(\tR\x11paymentMethodCode\"\x1d\n" +
	"\x1bDeletePaymentMethodResponse\"\x81\x02\n" +
	"\aWebhook\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12partner_payment_id\x18\x02 \x01(\tR\x10partnerPaymentId\x12,\n" +
	"\x12partner_event_type\x18\x03 \x01(\tR\x10partnerEventType\x12,\n" +
	"\x12partner_webhook_id\x18\x04 \x01(\tR\x10partnerWebhookId\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x18\n" +
	"\aheaders\x18\a \x01(\fR\aheaders\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload2\x8d\n" +
	"\n" +
	"\vCartService\x12]\n" +
	"\vHealthCheck\x12\x18.cart.HealthCheckRequest\x1a\x19.cart.HealthCheckResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/stripe/health\x12\x8b\x01\n" +
	"\x10GetPaymentMethod\x12\x1d.cart.GetPaymentMethodRequest\x1a\x1e.cart.GetPaymentMethodResponse\"8\x82\xd3\xe4\x93\x022\x120/v1/stripe/payment-methods/{payment_method_code}\x12{\n" +
	"\x12ListPaymentMethods\x12\x1f.cart.ListPaymentMethodsRequest\x1a .cart.ListPaymentMethodsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/stripe/payment-methods\x12\x9e\x01\n" +
	"\x13EnablePaymentMethod\x12 .cart.EnablePaymentMethodRequest\x1a!.cart.EnablePaymentMethodResponse\"B\x82\xd3\xe4\x93\x02<:\x01*\"7/v1/stripe/payment-methods/{payment_method_code}/enable\x12\xa2\x01\n" +
	"\x14DisablePaymentMethod\x12!.cart.DisablePaymentMethodRequest\x1a\".cart.DisablePaymentMethodResponse\"C\x82\xd3\xe4\x93\x02=:\x01*\"8/v1/stripe/payment-methods/{payment_method_code}/disable\x12\x94\x01\n" +
	"\x13DeletePaymentMethod\x12 .cart.DeletePaymentMethodRequest\x1a!.cart.DeletePaymentMethodResponse\"8\x82\xd3\xe4\x93\x022*0/v1/stripe/payment-methods/{payment_method_code}\x12h\n" +
	"\rCreatePayment\x12\x1a.cart.CreatePaymentRequest\x1a\x1b.cart.CreatePaymentResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/stripe/payments\x12u\n" +
	"\rUpdatePayment\x12\x1a.cart.UpdatePaymentRequest\x1a\x1b.cart.UpdatePaymentResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\x1a /v1/stripe/payments/{payment_id}\x12d\n" +
	"\fCreateRefund\x12\x19.cart.CreateRefundRequest\x1a\x1a.cart.CreateRefundResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/stripe/refunds\x12p\n" +
	"\fUpdateRefund\x12\x19.cart.UpdateRefundRequest\x1a\x1a.cart.UpdateRefundResponse\")\x82\xd3\xe4\x93\x02#:\x01*\x1a\x1e/v1/stripe/refunds/{refund_id}B\xb1\x02\x92A\xb5\x01\x12\xb2\x01\n" +
	"\x12Stripe Adapter API\x12\x96\x01Stripe payment adapter service API providing integration with Stripe payment processing including payment methods, transactions, and refund management2\x031.0\n" +
	"\bcom.cartB\tCartProtoP\x01Z1github.com/sundowndev/grpc-api-example/proto/cart\xa2\x02\x03CXX\xaa\x02\x04Cart\xca\x02\x04Cart\xe2\x02\x10Cart\\GPBMetadata\xea\x02\x04Cartb\x06proto3"

var (
	file_cart_cart_proto_rawDescOnce sync.Once
	file_cart_cart_proto_rawDescData []byte
)

func file_cart_cart_proto_rawDescGZIP() []byte {
	file_cart_cart_proto_rawDescOnce.Do(func() {
		file_cart_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_cart_proto_rawDesc), len(file_cart_cart_proto_rawDesc)))
	})
	return file_cart_cart_proto_rawDescData
}

var file_cart_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_cart_cart_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),           // 0: cart.HealthCheckRequest
	(*HealthCheckResponse)(nil),          // 1: cart.HealthCheckResponse
	(*CreatePaymentRequest)(nil),         // 2: cart.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),        // 3: cart.CreatePaymentResponse
	(*UpdatePaymentRequest)(nil),         // 4: cart.UpdatePaymentRequest
	(*UpdatePaymentResponse)(nil),        // 5: cart.UpdatePaymentResponse
	(*CreateRefundRequest)(nil),          // 6: cart.CreateRefundRequest
	(*CreateRefundResponse)(nil),         // 7: cart.CreateRefundResponse
	(*UpdateRefundRequest)(nil),          // 8: cart.UpdateRefundRequest
	(*UpdateRefundResponse)(nil),         // 9: cart.UpdateRefundResponse
	(*GetPaymentMethodRequest)(nil),      // 10: cart.GetPaymentMethodRequest
	(*GetPaymentMethodResponse)(nil),     // 11: cart.GetPaymentMethodResponse
	(*ListPaymentMethodsRequest)(nil),    // 12: cart.ListPaymentMethodsRequest
	(*ListPaymentMethodsResponse)(nil),   // 13: cart.ListPaymentMethodsResponse
	(*PaymentMethod)(nil),                // 14: cart.PaymentMethod
	(*Refund)(nil),                       // 15: cart.Refund
	(*RefundAttempt)(nil),                // 16: cart.RefundAttempt
	(*Payment)(nil),                      // 17: cart.Payment
	(*PaymentAttempt)(nil),               // 18: cart.PaymentAttempt
	(*EnablePaymentMethodRequest)(nil),   // 19: cart.EnablePaymentMethodRequest
	(*EnablePaymentMethodResponse)(nil),  // 20: cart.EnablePaymentMethodResponse
	(*DisablePaymentMethodRequest)(nil),  // 21: cart.DisablePaymentMethodRequest
	(*DisablePaymentMethodResponse)(nil), // 22: cart.DisablePaymentMethodResponse
	(*DeletePaymentMethodRequest)(nil),   // 23: cart.DeletePaymentMethodRequest
	(*DeletePaymentMethodResponse)(nil),  // 24: cart.DeletePaymentMethodResponse
	(*Webhook)(nil),                      // 25: cart.Webhook
	nil,                                  // 26: cart.UpdateRefundRequest.MetadataEntry
}
var file_cart_cart_proto_depIdxs = []int32{
	17, // 0: cart.CreatePaymentRequest.payment:type_name -> cart.Payment
	17, // 1: cart.CreatePaymentResponse.payment:type_name -> cart.Payment
	17, // 2: cart.UpdatePaymentRequest.payment:type_name -> cart.Payment
	25, // 3: cart.UpdatePaymentRequest.webhook:type_name -> cart.Webhook
	17, // 4: cart.UpdatePaymentResponse.payment:type_name -> cart.Payment
	17, // 5: cart.CreateRefundRequest.payment:type_name -> cart.Payment
	15, // 6: cart.CreateRefundRequest.refund:type_name -> cart.Refund
	15, // 7: cart.CreateRefundResponse.refund:type_name -> cart.Refund
	26, // 8: cart.UpdateRefundRequest.metadata:type_name -> cart.UpdateRefundRequest.MetadataEntry
	15, // 9: cart.UpdateRefundResponse.refund:type_name -> cart.Refund
	14, // 10: cart.GetPaymentMethodResponse.payment_method:type_name -> cart.PaymentMethod
	14, // 11: cart.ListPaymentMethodsResponse.payment_methods:type_name -> cart.PaymentMethod
	16, // 12: cart.Refund.attempts:type_name -> cart.RefundAttempt
	18, // 13: cart.Payment.attempts:type_name -> cart.PaymentAttempt
	15, // 14: cart.Payment.refunds:type_name -> cart.Refund
	0,  // 15: cart.CartService.HealthCheck:input_type -> cart.HealthCheckRequest
	10, // 16: cart.CartService.GetPaymentMethod:input_type -> cart.GetPaymentMethodRequest
	12, // 17: cart.CartService.ListPaymentMethods:input_type -> cart.ListPaymentMethodsRequest
	19, // 18: cart.CartService.EnablePaymentMethod:input_type -> cart.EnablePaymentMethodRequest
	21, // 19: cart.CartService.DisablePaymentMethod:input_type -> cart.DisablePaymentMethodRequest
	23, // 20: cart.CartService.DeletePaymentMethod:input_type -> cart.DeletePaymentMethodRequest
	2,  // 21: cart.CartService.CreatePayment:input_type -> cart.CreatePaymentRequest
	4,  // 22: cart.CartService.UpdatePayment:input_type -> cart.UpdatePaymentRequest
	6,  // 23: cart.CartService.CreateRefund:input_type -> cart.CreateRefundRequest
	8,  // 24: cart.CartService.UpdateRefund:input_type -> cart.UpdateRefundRequest
	1,  // 25: cart.CartService.HealthCheck:output_type -> cart.HealthCheckResponse
	11, // 26: cart.CartService.GetPaymentMethod:output_type -> cart.GetPaymentMethodResponse
	13, // 27: cart.CartService.ListPaymentMethods:output_type -> cart.ListPaymentMethodsResponse
	20, // 28: cart.CartService.EnablePaymentMethod:output_type -> cart.EnablePaymentMethodResponse
	22, // 29: cart.CartService.DisablePaymentMethod:output_type -> cart.DisablePaymentMethodResponse
	24, // 30: cart.CartService.DeletePaymentMethod:output_type -> cart.DeletePaymentMethodResponse
	3,  // 31: cart.CartService.CreatePayment:output_type -> cart.CreatePaymentResponse
	5,  // 32: cart.CartService.UpdatePayment:output_type -> cart.UpdatePaymentResponse
	7,  // 33: cart.CartService.CreateRefund:output_type -> cart.CreateRefundResponse
	9,  // 34: cart.CartService.UpdateRefund:output_type -> cart.UpdateRefundResponse
	25, // [25:35] is the sub-list for method output_type
	15, // [15:25] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_cart_cart_proto_init() }
func file_cart_cart_proto_init() {
	if File_cart_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_cart_proto_rawDesc), len(file_cart_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_cart_proto_goTypes,
		DependencyIndexes: file_cart_cart_proto_depIdxs,
		MessageInfos:      file_cart_cart_proto_msgTypes,
	}.Build()
	File_cart_cart_proto = out.File
	file_cart_cart_proto_goTypes = nil
	file_cart_cart_proto_depIdxs = nil
}
