// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: payments/payment_methods.proto

package payments

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentMethodStatus represents the status of a payment method
type PaymentMethodStatus int32

const (
	PaymentMethodStatus_PAYMENT_METHOD_STATUS_UNSPECIFIED PaymentMethodStatus = 0
	PaymentMethodStatus_PAYMENT_METHOD_STATUS_ACTIVE      PaymentMethodStatus = 1
	PaymentMethodStatus_PAYMENT_METHOD_STATUS_INACTIVE    PaymentMethodStatus = 2
)

// Enum value maps for PaymentMethodStatus.
var (
	PaymentMethodStatus_name = map[int32]string{
		0: "PAYMENT_METHOD_STATUS_UNSPECIFIED",
		1: "PAYMENT_METHOD_STATUS_ACTIVE",
		2: "PAYMENT_METHOD_STATUS_INACTIVE",
	}
	PaymentMethodStatus_value = map[string]int32{
		"PAYMENT_METHOD_STATUS_UNSPECIFIED": 0,
		"PAYMENT_METHOD_STATUS_ACTIVE":      1,
		"PAYMENT_METHOD_STATUS_INACTIVE":    2,
	}
)

func (x PaymentMethodStatus) Enum() *PaymentMethodStatus {
	p := new(PaymentMethodStatus)
	*p = x
	return p
}

func (x PaymentMethodStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethodStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payments_payment_methods_proto_enumTypes[0].Descriptor()
}

func (PaymentMethodStatus) Type() protoreflect.EnumType {
	return &file_payments_payment_methods_proto_enumTypes[0]
}

func (x PaymentMethodStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethodStatus.Descriptor instead.
func (PaymentMethodStatus) EnumDescriptor() ([]byte, []int) {
	return file_payments_payment_methods_proto_rawDescGZIP(), []int{0}
}

// PaymentMethod represents a payment method
type PaymentMethod struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentMethodCode string                 `protobuf:"bytes,2,opt,name=payment_method_code,json=paymentMethodCode,proto3" json:"payment_method_code,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status            PaymentMethodStatus    `protobuf:"varint,5,opt,name=status,proto3,enum=payments.PaymentMethodStatus" json:"status,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PaymentMethod) Reset() {
	*x = PaymentMethod{}
	mi := &file_payments_payment_methods_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethod) ProtoMessage() {}

func (x *PaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_payments_payment_methods_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethod.ProtoReflect.Descriptor instead.
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return file_payments_payment_methods_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentMethod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentMethod) GetPaymentMethodCode() string {
	if x != nil {
		return x.PaymentMethodCode
	}
	return ""
}

func (x *PaymentMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PaymentMethod) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PaymentMethod) GetStatus() PaymentMethodStatus {
	if x != nil {
		return x.Status
	}
	return PaymentMethodStatus_PAYMENT_METHOD_STATUS_UNSPECIFIED
}

func (x *PaymentMethod) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PaymentMethod) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PaymentMethod) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// GetPaymentMethodRequest represents a request to get a payment method
type GetPaymentMethodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentMethodRequest) Reset() {
	*x = GetPaymentMethodRequest{}
	mi := &file_payments_payment_methods_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentMethodRequest) ProtoMessage() {}

func (x *GetPaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_payment_methods_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_payments_payment_methods_proto_rawDescGZIP(), []int{1}
}

func (x *GetPaymentMethodRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetPaymentMethodResponse represents a response to getting a payment method
type GetPaymentMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethod *PaymentMethod         `protobuf:"bytes,1,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentMethodResponse) Reset() {
	*x = GetPaymentMethodResponse{}
	mi := &file_payments_payment_methods_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentMethodResponse) ProtoMessage() {}

func (x *GetPaymentMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_payment_methods_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentMethodResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentMethodResponse) Descriptor() ([]byte, []int) {
	return file_payments_payment_methods_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentMethodResponse) GetPaymentMethod() *PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

// ListPaymentMethodsRequest represents a request to list payment methods
type ListPaymentMethodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentMethodsRequest) Reset() {
	*x = ListPaymentMethodsRequest{}
	mi := &file_payments_payment_methods_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentMethodsRequest) ProtoMessage() {}

func (x *ListPaymentMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_payment_methods_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentMethodsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentMethodsRequest) Descriptor() ([]byte, []int) {
	return file_payments_payment_methods_proto_rawDescGZIP(), []int{3}
}

// ListPaymentMethodsResponse represents a response to listing payment methods
type ListPaymentMethodsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethods []*PaymentMethod       `protobuf:"bytes,1,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListPaymentMethodsResponse) Reset() {
	*x = ListPaymentMethodsResponse{}
	mi := &file_payments_payment_methods_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentMethodsResponse) ProtoMessage() {}

func (x *ListPaymentMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_payment_methods_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentMethodsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentMethodsResponse) Descriptor() ([]byte, []int) {
	return file_payments_payment_methods_proto_rawDescGZIP(), []int{4}
}

func (x *ListPaymentMethodsResponse) GetPaymentMethods() []*PaymentMethod {
	if x != nil {
		return x.PaymentMethods
	}
	return nil
}

var File_payments_payment_methods_proto protoreflect.FileDescriptor

const file_payments_payment_methods_proto_rawDesc = "" +
	"\n" +
	"\x1epayments/payment_methods.proto\x12\bpayments\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x02\n" +
	"\rPaymentMethod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x13payment_method_code\x18\x02 \x01(\tR\x11paymentMethodCode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x125\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1d.payments.PaymentMethodStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\")\n" +
	"\x17GetPaymentMethodRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Z\n" +
	"\x18GetPaymentMethodResponse\x12>\n" +
	"\x0epayment_method\x18\x01 \x01(\v2\x17.payments.PaymentMethodR\rpaymentMethod\"\x1b\n" +
	"\x19ListPaymentMethodsRequest\"^\n" +
	"\x1aListPaymentMethodsResponse\x12@\n" +
	"\x0fpayment_methods\x18\x01 \x03(\v2\x17.payments.PaymentMethodR\x0epaymentMethods*\x82\x01\n" +
	"\x13PaymentMethodStatus\x12%\n" +
	"!PAYMENT_METHOD_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPAYMENT_METHOD_STATUS_ACTIVE\x10\x01\x12\"\n" +
	"\x1ePAYMENT_METHOD_STATUS_INACTIVE\x10\x022\xd6\x01\n" +
	"\x14PaymentMethodService\x12[\n" +
	"\x10GetPaymentMethod\x12!.payments.GetPaymentMethodRequest\x1a\".payments.GetPaymentMethodResponse\"\x00\x12a\n" +
	"\x12ListPaymentMethods\x12#.payments.ListPaymentMethodsRequest\x1a$.payments.ListPaymentMethodsResponse\"\x00B\x9a\x01\n" +
	"\fcom.paymentsB\x13PaymentMethodsProtoP\x01Z5github.com/sundowndev/grpc-api-example/proto/payments\xa2\x02\x03PXX\xaa\x02\bPayments\xca\x02\bPayments\xe2\x02\x14Payments\\GPBMetadata\xea\x02\bPaymentsb\x06proto3"

var (
	file_payments_payment_methods_proto_rawDescOnce sync.Once
	file_payments_payment_methods_proto_rawDescData []byte
)

func file_payments_payment_methods_proto_rawDescGZIP() []byte {
	file_payments_payment_methods_proto_rawDescOnce.Do(func() {
		file_payments_payment_methods_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payments_payment_methods_proto_rawDesc), len(file_payments_payment_methods_proto_rawDesc)))
	})
	return file_payments_payment_methods_proto_rawDescData
}

var file_payments_payment_methods_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payments_payment_methods_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_payments_payment_methods_proto_goTypes = []any{
	(PaymentMethodStatus)(0),           // 0: payments.PaymentMethodStatus
	(*PaymentMethod)(nil),              // 1: payments.PaymentMethod
	(*GetPaymentMethodRequest)(nil),    // 2: payments.GetPaymentMethodRequest
	(*GetPaymentMethodResponse)(nil),   // 3: payments.GetPaymentMethodResponse
	(*ListPaymentMethodsRequest)(nil),  // 4: payments.ListPaymentMethodsRequest
	(*ListPaymentMethodsResponse)(nil), // 5: payments.ListPaymentMethodsResponse
	(*timestamppb.Timestamp)(nil),      // 6: google.protobuf.Timestamp
}
var file_payments_payment_methods_proto_depIdxs = []int32{
	0, // 0: payments.PaymentMethod.status:type_name -> payments.PaymentMethodStatus
	6, // 1: payments.PaymentMethod.created_at:type_name -> google.protobuf.Timestamp
	6, // 2: payments.PaymentMethod.updated_at:type_name -> google.protobuf.Timestamp
	6, // 3: payments.PaymentMethod.deleted_at:type_name -> google.protobuf.Timestamp
	1, // 4: payments.GetPaymentMethodResponse.payment_method:type_name -> payments.PaymentMethod
	1, // 5: payments.ListPaymentMethodsResponse.payment_methods:type_name -> payments.PaymentMethod
	2, // 6: payments.PaymentMethodService.GetPaymentMethod:input_type -> payments.GetPaymentMethodRequest
	4, // 7: payments.PaymentMethodService.ListPaymentMethods:input_type -> payments.ListPaymentMethodsRequest
	3, // 8: payments.PaymentMethodService.GetPaymentMethod:output_type -> payments.GetPaymentMethodResponse
	5, // 9: payments.PaymentMethodService.ListPaymentMethods:output_type -> payments.ListPaymentMethodsResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_payments_payment_methods_proto_init() }
func file_payments_payment_methods_proto_init() {
	if File_payments_payment_methods_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payments_payment_methods_proto_rawDesc), len(file_payments_payment_methods_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payments_payment_methods_proto_goTypes,
		DependencyIndexes: file_payments_payment_methods_proto_depIdxs,
		EnumInfos:         file_payments_payment_methods_proto_enumTypes,
		MessageInfos:      file_payments_payment_methods_proto_msgTypes,
	}.Build()
	File_payments_payment_methods_proto = out.File
	file_payments_payment_methods_proto_goTypes = nil
	file_payments_payment_methods_proto_depIdxs = nil
}
