// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: payments/refunds.proto

package payments

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RefundStatus represents the status of a refund
type RefundStatus int32

const (
	RefundStatus_REFUND_STATUS_UNSPECIFIED RefundStatus = 0
	RefundStatus_REFUND_STATUS_PENDING     RefundStatus = 1
	RefundStatus_REFUND_STATUS_COMPLETED   RefundStatus = 2
	RefundStatus_REFUND_STATUS_FAILED      RefundStatus = 3
)

// Enum value maps for RefundStatus.
var (
	RefundStatus_name = map[int32]string{
		0: "REFUND_STATUS_UNSPECIFIED",
		1: "REFUND_STATUS_PENDING",
		2: "REFUND_STATUS_COMPLETED",
		3: "REFUND_STATUS_FAILED",
	}
	RefundStatus_value = map[string]int32{
		"REFUND_STATUS_UNSPECIFIED": 0,
		"REFUND_STATUS_PENDING":     1,
		"REFUND_STATUS_COMPLETED":   2,
		"REFUND_STATUS_FAILED":      3,
	}
)

func (x RefundStatus) Enum() *RefundStatus {
	p := new(RefundStatus)
	*p = x
	return p
}

func (x RefundStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefundStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payments_refunds_proto_enumTypes[0].Descriptor()
}

func (RefundStatus) Type() protoreflect.EnumType {
	return &file_payments_refunds_proto_enumTypes[0]
}

func (x RefundStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefundStatus.Descriptor instead.
func (RefundStatus) EnumDescriptor() ([]byte, []int) {
	return file_payments_refunds_proto_rawDescGZIP(), []int{0}
}

// Refund represents a refund in the system
type Refund struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Status        RefundStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=payments.RefundStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Refund) Reset() {
	*x = Refund{}
	mi := &file_payments_refunds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refund) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refund) ProtoMessage() {}

func (x *Refund) ProtoReflect() protoreflect.Message {
	mi := &file_payments_refunds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refund.ProtoReflect.Descriptor instead.
func (*Refund) Descriptor() ([]byte, []int) {
	return file_payments_refunds_proto_rawDescGZIP(), []int{0}
}

func (x *Refund) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Refund) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Refund) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Refund) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Refund) GetStatus() RefundStatus {
	if x != nil {
		return x.Status
	}
	return RefundStatus_REFUND_STATUS_UNSPECIFIED
}

func (x *Refund) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Refund) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateRefundRequest represents a request to create a refund
type CreateRefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRefundRequest) Reset() {
	*x = CreateRefundRequest{}
	mi := &file_payments_refunds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRefundRequest) ProtoMessage() {}

func (x *CreateRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_refunds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRefundRequest.ProtoReflect.Descriptor instead.
func (*CreateRefundRequest) Descriptor() ([]byte, []int) {
	return file_payments_refunds_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRefundRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreateRefundRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateRefundRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// CreateRefundResponse represents a response to creating a refund
type CreateRefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refund        *Refund                `protobuf:"bytes,1,opt,name=refund,proto3" json:"refund,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRefundResponse) Reset() {
	*x = CreateRefundResponse{}
	mi := &file_payments_refunds_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRefundResponse) ProtoMessage() {}

func (x *CreateRefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_refunds_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRefundResponse.ProtoReflect.Descriptor instead.
func (*CreateRefundResponse) Descriptor() ([]byte, []int) {
	return file_payments_refunds_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRefundResponse) GetRefund() *Refund {
	if x != nil {
		return x.Refund
	}
	return nil
}

// GetRefundRequest represents a request to get a refund
type GetRefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRefundRequest) Reset() {
	*x = GetRefundRequest{}
	mi := &file_payments_refunds_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRefundRequest) ProtoMessage() {}

func (x *GetRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_refunds_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRefundRequest.ProtoReflect.Descriptor instead.
func (*GetRefundRequest) Descriptor() ([]byte, []int) {
	return file_payments_refunds_proto_rawDescGZIP(), []int{3}
}

func (x *GetRefundRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetRefundResponse represents a response to getting a refund
type GetRefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refund        *Refund                `protobuf:"bytes,1,opt,name=refund,proto3" json:"refund,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRefundResponse) Reset() {
	*x = GetRefundResponse{}
	mi := &file_payments_refunds_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRefundResponse) ProtoMessage() {}

func (x *GetRefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_refunds_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRefundResponse.ProtoReflect.Descriptor instead.
func (*GetRefundResponse) Descriptor() ([]byte, []int) {
	return file_payments_refunds_proto_rawDescGZIP(), []int{4}
}

func (x *GetRefundResponse) GetRefund() *Refund {
	if x != nil {
		return x.Refund
	}
	return nil
}

// ListRefundsByPaymentRequest represents a request to list refunds by payment
// ID
type ListRefundsByPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRefundsByPaymentRequest) Reset() {
	*x = ListRefundsByPaymentRequest{}
	mi := &file_payments_refunds_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRefundsByPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRefundsByPaymentRequest) ProtoMessage() {}

func (x *ListRefundsByPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_refunds_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRefundsByPaymentRequest.ProtoReflect.Descriptor instead.
func (*ListRefundsByPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payments_refunds_proto_rawDescGZIP(), []int{5}
}

func (x *ListRefundsByPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

// ListRefundsByPaymentResponse represents a response to listing refunds by
// payment ID
type ListRefundsByPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refunds       []*Refund              `protobuf:"bytes,1,rep,name=refunds,proto3" json:"refunds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRefundsByPaymentResponse) Reset() {
	*x = ListRefundsByPaymentResponse{}
	mi := &file_payments_refunds_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRefundsByPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRefundsByPaymentResponse) ProtoMessage() {}

func (x *ListRefundsByPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_refunds_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRefundsByPaymentResponse.ProtoReflect.Descriptor instead.
func (*ListRefundsByPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payments_refunds_proto_rawDescGZIP(), []int{6}
}

func (x *ListRefundsByPaymentResponse) GetRefunds() []*Refund {
	if x != nil {
		return x.Refunds
	}
	return nil
}

// UpdateRefundStatusRequest represents a request to update a refund status
type UpdateRefundStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        RefundStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=payments.RefundStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRefundStatusRequest) Reset() {
	*x = UpdateRefundStatusRequest{}
	mi := &file_payments_refunds_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRefundStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRefundStatusRequest) ProtoMessage() {}

func (x *UpdateRefundStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_refunds_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRefundStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateRefundStatusRequest) Descriptor() ([]byte, []int) {
	return file_payments_refunds_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRefundStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRefundStatusRequest) GetStatus() RefundStatus {
	if x != nil {
		return x.Status
	}
	return RefundStatus_REFUND_STATUS_UNSPECIFIED
}

// UpdateRefundStatusResponse represents a response to updating a refund status
type UpdateRefundStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refund        *Refund                `protobuf:"bytes,1,opt,name=refund,proto3" json:"refund,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRefundStatusResponse) Reset() {
	*x = UpdateRefundStatusResponse{}
	mi := &file_payments_refunds_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRefundStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRefundStatusResponse) ProtoMessage() {}

func (x *UpdateRefundStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_refunds_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRefundStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateRefundStatusResponse) Descriptor() ([]byte, []int) {
	return file_payments_refunds_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRefundStatusResponse) GetRefund() *Refund {
	if x != nil {
		return x.Refund
	}
	return nil
}

var File_payments_refunds_proto protoreflect.FileDescriptor

const file_payments_refunds_proto_rawDesc = "" +
	"\n" +
	"\x16payments/refunds.proto\x12\bpayments\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x02\n" +
	"\x06Refund\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12.\n" +
	"\x06status\x18\x05 \x01(\x0e2\x16.payments.RefundStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"d\n" +
	"\x13CreateRefundRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"@\n" +
	"\x14CreateRefundResponse\x12(\n" +
	"\x06refund\x18\x01 \x01(\v2\x10.payments.RefundR\x06refund\"\"\n" +
	"\x10GetRefundRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x11GetRefundResponse\x12(\n" +
	"\x06refund\x18\x01 \x01(\v2\x10.payments.RefundR\x06refund\"<\n" +
	"\x1bListRefundsByPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"J\n" +
	"\x1cListRefundsByPaymentResponse\x12*\n" +
	"\arefunds\x18\x01 \x03(\v2\x10.payments.RefundR\arefunds\"[\n" +
	"\x19UpdateRefundStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.payments.RefundStatusR\x06status\"F\n" +
	"\x1aUpdateRefundStatusResponse\x12(\n" +
	"\x06refund\x18\x01 \x01(\v2\x10.payments.RefundR\x06refund*\x7f\n" +
	"\fRefundStatus\x12\x1d\n" +
	"\x19REFUND_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REFUND_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17REFUND_STATUS_COMPLETED\x10\x02\x12\x18\n" +
	"\x14REFUND_STATUS_FAILED\x10\x032\xf4\x02\n" +
	"\rRefundService\x12O\n" +
	"\fCreateRefund\x12\x1d.payments.CreateRefundRequest\x1a\x1e.payments.CreateRefundResponse\"\x00\x12F\n" +
	"\tGetRefund\x12\x1a.payments.GetRefundRequest\x1a\x1b.payments.GetRefundResponse\"\x00\x12g\n" +
	"\x14ListRefundsByPayment\x12%.payments.ListRefundsByPaymentRequest\x1a&.payments.ListRefundsByPaymentResponse\"\x00\x12a\n" +
	"\x12UpdateRefundStatus\x12#.payments.UpdateRefundStatusRequest\x1a$.payments.UpdateRefundStatusResponse\"\x00B\x93\x01\n" +
	"\fcom.paymentsB\fRefundsProtoP\x01Z5github.com/sundowndev/grpc-api-example/proto/payments\xa2\x02\x03PXX\xaa\x02\bPayments\xca\x02\bPayments\xe2\x02\x14Payments\\GPBMetadata\xea\x02\bPaymentsb\x06proto3"

var (
	file_payments_refunds_proto_rawDescOnce sync.Once
	file_payments_refunds_proto_rawDescData []byte
)

func file_payments_refunds_proto_rawDescGZIP() []byte {
	file_payments_refunds_proto_rawDescOnce.Do(func() {
		file_payments_refunds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payments_refunds_proto_rawDesc), len(file_payments_refunds_proto_rawDesc)))
	})
	return file_payments_refunds_proto_rawDescData
}

var file_payments_refunds_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payments_refunds_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_payments_refunds_proto_goTypes = []any{
	(RefundStatus)(0),                    // 0: payments.RefundStatus
	(*Refund)(nil),                       // 1: payments.Refund
	(*CreateRefundRequest)(nil),          // 2: payments.CreateRefundRequest
	(*CreateRefundResponse)(nil),         // 3: payments.CreateRefundResponse
	(*GetRefundRequest)(nil),             // 4: payments.GetRefundRequest
	(*GetRefundResponse)(nil),            // 5: payments.GetRefundResponse
	(*ListRefundsByPaymentRequest)(nil),  // 6: payments.ListRefundsByPaymentRequest
	(*ListRefundsByPaymentResponse)(nil), // 7: payments.ListRefundsByPaymentResponse
	(*UpdateRefundStatusRequest)(nil),    // 8: payments.UpdateRefundStatusRequest
	(*UpdateRefundStatusResponse)(nil),   // 9: payments.UpdateRefundStatusResponse
	(*timestamppb.Timestamp)(nil),        // 10: google.protobuf.Timestamp
}
var file_payments_refunds_proto_depIdxs = []int32{
	0,  // 0: payments.Refund.status:type_name -> payments.RefundStatus
	10, // 1: payments.Refund.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: payments.Refund.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: payments.CreateRefundResponse.refund:type_name -> payments.Refund
	1,  // 4: payments.GetRefundResponse.refund:type_name -> payments.Refund
	1,  // 5: payments.ListRefundsByPaymentResponse.refunds:type_name -> payments.Refund
	0,  // 6: payments.UpdateRefundStatusRequest.status:type_name -> payments.RefundStatus
	1,  // 7: payments.UpdateRefundStatusResponse.refund:type_name -> payments.Refund
	2,  // 8: payments.RefundService.CreateRefund:input_type -> payments.CreateRefundRequest
	4,  // 9: payments.RefundService.GetRefund:input_type -> payments.GetRefundRequest
	6,  // 10: payments.RefundService.ListRefundsByPayment:input_type -> payments.ListRefundsByPaymentRequest
	8,  // 11: payments.RefundService.UpdateRefundStatus:input_type -> payments.UpdateRefundStatusRequest
	3,  // 12: payments.RefundService.CreateRefund:output_type -> payments.CreateRefundResponse
	5,  // 13: payments.RefundService.GetRefund:output_type -> payments.GetRefundResponse
	7,  // 14: payments.RefundService.ListRefundsByPayment:output_type -> payments.ListRefundsByPaymentResponse
	9,  // 15: payments.RefundService.UpdateRefundStatus:output_type -> payments.UpdateRefundStatusResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_payments_refunds_proto_init() }
func file_payments_refunds_proto_init() {
	if File_payments_refunds_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payments_refunds_proto_rawDesc), len(file_payments_refunds_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payments_refunds_proto_goTypes,
		DependencyIndexes: file_payments_refunds_proto_depIdxs,
		EnumInfos:         file_payments_refunds_proto_enumTypes,
		MessageInfos:      file_payments_refunds_proto_msgTypes,
	}.Build()
	File_payments_refunds_proto = out.File
	file_payments_refunds_proto_goTypes = nil
	file_payments_refunds_proto_depIdxs = nil
}
